### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by hkmztrk** [EBjerrum/SMILES-enumeration#2]
Hello,

I read your paper and found it really interesting. I will try to use enumerated SMILES in my study as well. I think you have updated your code recently, because the script to enumerate SMILES I was working on looks different than the current one. I'd like to know how they are different from each other.

Thanks!

The one I was using:
`canonical, s = get_mol_set(ligands[ligid], tries=10)`

The current one:
```
for i in range(10):
    print sme.randomize_smiles("CCC(=O)O[C@@]1(CC[NH+](C[C@H]1CC=C)C)c2ccccc2")
```

**Comment by EBjerrum** [comment]
Sorry, missed your comment. Seems pretty old now, hope you solved it.
