### ISSUE TITLE
Make it installable by pip 

### ISSUE THREAD

**Issue by hsiaoyi0504** [EBjerrum/SMILES-enumeration#3]
As title, with this change, we can make this tool more useful.

**Comment by Abdulk084** [comment]
I agree!!!!

**Comment by EBjerrum** [comment]
Thanks for the interest in the code. I would encourage you to take a look at the molvecgen package. 

https://github.com/EBjerrum/molvecgen 

It has an installer, but is not on pip as such. 

However, can be installed with pip with 

python -m pip install git+https://github.com/EBjerrum/molvecgen
