### ISSUE TITLE
How to use it? I'm getting: Unbalanced generation of batches

### ISSUE THREAD

**Issue by Fatima-Aslam** [EBjerrum/SMILES-enumeration#6]
Hi,
Can you please guide me, how to use it?
When I use this command
                  python SmilesEnumerator.py
I  got this
                 Unbalanced generation of batches
Thank you!

**Comment by EBjerrum** [comment]
It's a python object, so you need to import the class in python and use it there, look at the readme.md for instructions. If you just run it from the command line it will run some standard tests.

**Comment by EBjerrum** [comment]
Closed due to inactivity
