### ISSUE TITLE
installation issue?

### ISSUE THREAD

**Issue by amarye** [EBjerrum/SMILES-enumeration#8]
![Screenshot from 2022-10-28 09-44-00](https://user-images.githubusercontent.com/55770700/198446403-bf5217b9-663a-491d-bec8-cfd8c085f98a.png)

I have installed rdkit, but the code did not work.
Could you please help me to solve this issue?

**Comment by EBjerrum** [comment]
Can you run ipython or python directly and import rdkit? This has more likely something to do with your installation than the Smiles-Enumeration package. I can see that you are trying to run the code via a jupyter notebook, do  you have the right kernel active?
