### ISSUE TITLE
How to install SmilesEnumerator in spyder？

### ISSUE THREAD

**Issue by qxq605215504** [EBjerrum/SMILES-enumeration#9]
Hello. I encountered the following error when installing using the Anaconda prompt. 
ERROR: Could not find a version that satisfies the requirement SmilesEnumerator (from versions: none)
ERROR: No matching distribution found for SmilesEnumerator
How can I resolve this issue?
![微信截图_20240618161049](https://github.com/EBjerrum/SMILES-enumeration/assets/167766358/fbd0c754-b5e9-4e61-bb3e-92283bca40e1)

**Comment by EBjerrum** [comment]
It's not a package on PyPI. It's not even a package as such as I never got around to create an installer for this. You simply drop the file SmilesEnumerator.py in your workdirectory and import from that. Alternative we developed another package, https://github.com/MolecularAI/pysmilesutils when I was at AstraZeneca. It's more supportive of Pytorch, but also has a lot of other features and customizability that SMILES enumerator doesn't have.

**Comment by qxq605215504** [comment]
Thank you for your response. I have successfully managed to enumerate SMILES strings. Additionally,Additionally, I would like to seek your help with two other questions.
1、Currently, the enumerator can generate 10 SMILES strings at a time. Is it possible to adjust the code to enable the enumerator to generate more SMILES strings at once?
2、Have you considered upgrading the code to support the enumeration of BigSMILES strings?

**Comment by EBjerrum** [comment]
I think you may be mixing up the batch_size with enumeration size?? Do you want batches of different smiles strings that are all augmented? Or you want many versions of the same smiles string? The batch size can be defined for the SmilesIterator, and if you want multiple examples for the same smiles string, it's straightforward to use the enumerator in a loop.
```
for i in range(10):
    print(sme.randomize_smiles("CCC(=O)O[C@@]1(CC[NH+](C[C@H]1CC=C)C)c2ccccc2"))
```

No, I have not considered upgrading the code to support BigSMILES strings. I don't work with those myself, and are currently not really maintaining this old code.

**Comment by qxq605215504** [comment]
Thank you very much for your response. I indeed want many versions of the same smiles string. With your help, I have successfully resolved this issue.
Once again, I extend my sincere gratitude for your assistance.
